name: Deploy to EC2 via S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 \
            --build-arg ENV_LOCAL_CONTENT="${{ secrets.ENV_LOCAL_CONTENT }}" \
            -t inkv-image .
          docker save -o inkv.tar inkv-image

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"

      - name: Upload Docker Image to S3
        run: |
          echo "ğŸš€ S3ì— Docker ì´ë¯¸ì§€ ì—…ë¡œë“œ ì¤‘..."
          aws s3 cp inkv.tar s3://clienttbucket/inkv.tar
          echo "âœ… Docker ì´ë¯¸ì§€ S3 ì—…ë¡œë“œ ì™„ë£Œ!"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws s3 cp s3://clienttbucket/inkv.tar /home/ubuntu/inkv.tar
            docker load -i /home/ubuntu/inkv.tar 
            docker stop inkv-container || true
            docker rm inkv-container || true
            docker run -d --name inkv-container -p 3000:3000 \
              -e ENV_LOCAL_CONTENT="${{ secrets.ENV_LOCAL_CONTENT }}" \
              inkv-image

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Spidey Bot", "content": "ğŸ•·ï¸ **ë°°í¬ ì™„ë£Œ!** ğŸš€\nğŸ”— https://moim.team"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}